(function(root,factory){
'use strict';
const api=factory(root);
if(typeof module==='object'&&module.exports)module.exports=api;
else{root.Move28=root.Move28||{};root.Move28.domain=Object.assign(root.Move28.domain||{},api)}
})(globalThis,function(root){
'use strict';
const SafeArray=Array,SafeSet=Set,SafeWeakSet=WeakSet,nativeObjectPrototype=Object.prototype;
const safeArrayIsArray=Array.isArray,safeGetPrototypeOf=Object.getPrototypeOf,safeGetOwnPropertyDescriptor=Object.getOwnPropertyDescriptor,safeGetOwnPropertyDescriptors=Object.getOwnPropertyDescriptors,safeObjectKeys=Object.keys,safeFreeze=Object.freeze,safeObjectIs=Object.is;
const safeOwnKeys=Reflect.ownKeys,safeNumberIsFinite=Number.isFinite,safeNumberIsSafeInteger=Number.isSafeInteger;
const safeHasOwn=Function.prototype.call.bind(Object.prototype.hasOwnProperty),safePush=Function.prototype.call.bind(Array.prototype.push),safePop=Function.prototype.call.bind(Array.prototype.pop),safeIncludes=Function.prototype.call.bind(Array.prototype.includes),safeIndexOf=Function.prototype.call.bind(Array.prototype.indexOf),safeRegexTest=Function.prototype.call.bind(RegExp.prototype.test);
const safeWeakHas=Function.prototype.call.bind(WeakSet.prototype.has),safeWeakAdd=Function.prototype.call.bind(WeakSet.prototype.add),safeSetHas=Function.prototype.call.bind(Set.prototype.has),safeSetAdd=Function.prototype.call.bind(Set.prototype.add);
const safeString=String,safeMathFloor=Math.floor,safeMathAbs=Math.abs;
const nativeStructuredClone=typeof root.structuredClone==='function'?root.structuredClone.bind(root):null;
const WEEKDAYS=safeFreeze(['mon','tue','wed','thu','fri','sat','sun']),INTENTS=safeFreeze(['full_body_strength','low_impact_cardio','recovery']),INPUT_FIELDS=safeFreeze(['plan','currentWeekNumber','sessionId','intake','completedLogs','allowedThroughWeekNumber']);
const DANGEROUS=new SafeSet(['__proto__','prototype','constructor']);
const MACHINE_ID=/^[a-z0-9][a-z0-9._-]{0,127}$/,UTC_ISO=/^(?:\d{4})-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/;
const LOG_FIELDS=safeFreeze(['planId','sessionId','status','completedAt','adaptationId','capabilityRevision','feedbackCode','feedbackAt']);
const INTRINSICS=safeFreeze([[root,'String',safeString],[Array,'isArray',safeArrayIsArray],[Array.prototype,'push',Array.prototype.push],[Array.prototype,'pop',Array.prototype.pop],[Array.prototype,'includes',Array.prototype.includes],[Array.prototype,'indexOf',Array.prototype.indexOf],[Object,'getPrototypeOf',safeGetPrototypeOf],[Object,'getOwnPropertyDescriptor',safeGetOwnPropertyDescriptor],[Object,'getOwnPropertyDescriptors',safeGetOwnPropertyDescriptors],[Object,'keys',safeObjectKeys],[Object,'freeze',safeFreeze],[Object,'is',safeObjectIs],[Reflect,'ownKeys',safeOwnKeys],[Number,'isFinite',safeNumberIsFinite],[Number,'isSafeInteger',safeNumberIsSafeInteger],[Math,'floor',safeMathFloor],[Math,'abs',safeMathAbs],[RegExp.prototype,'test',RegExp.prototype.test],[Set.prototype,'has',Set.prototype.has],[Set.prototype,'add',Set.prototype.add],[WeakSet.prototype,'has',WeakSet.prototype.has],[WeakSet.prototype,'add',WeakSet.prototype.add]]);
function intrinsicsIntact(){try{for(let index=0;index<INTRINSICS.length;index+=1){const item=INTRINSICS[index],descriptor=safeGetOwnPropertyDescriptor(item[0],item[1]);if(!descriptor||!safeHasOwn(descriptor,'value')||descriptor.value!==item[2])return false}return true}catch(_error){return false}}
function plainRecord(value){if(!value||typeof value!=='object'||safeArrayIsArray(value))return false;try{const prototype=safeGetPrototypeOf(value);return prototype===null||prototype===nativeObjectPrototype}catch(_error){return false}}
function clonePureData(value){if(!nativeStructuredClone)return null;try{const pending=[{value,depth:0}],seen=new SafeWeakSet();let nodes=0;while(pending.length){const frame=safePop(pending),current=frame.value;if(current===null||typeof current==='string'||typeof current==='boolean')continue;if(typeof current==='number'){if(!safeNumberIsFinite(current)||safeObjectIs(current,-0))return null;continue}if(!current||typeof current!=='object'||safeWeakHas(seen,current)||frame.depth>32)return null;safeWeakAdd(seen,current);if(++nodes>8192)return null;const array=safeArrayIsArray(current);if(!array&&!plainRecord(current))return null;const descriptors=safeGetOwnPropertyDescriptors(current),keys=safeOwnKeys(descriptors);if(keys.length>1024)return null;if(array){const length=descriptors.length;if(!length||!safeHasOwn(length,'value')||!safeNumberIsSafeInteger(length.value)||length.value<0||length.value>512||keys.length!==length.value+1)return null;for(let index=0;index<length.value;index+=1)if(!safeHasOwn(descriptors,safeString(index)))return null}for(let index=0;index<keys.length;index+=1){const key=keys[index];if(typeof key!=='string'||safeSetHas(DANGEROUS,key))return null;if(array&&key==='length')continue;const descriptor=descriptors[key];if(!descriptor||!safeHasOwn(descriptor,'value'))return null;safePush(pending,{value:descriptor.value,depth:frame.depth+1})}}return nativeStructuredClone(value)}catch(_error){return null}}
function deepFreeze(value,seen=new SafeWeakSet()){if(!value||typeof value!=='object'||safeWeakHas(seen,value))return value;safeWeakAdd(seen,value);const keys=safeObjectKeys(value);for(let index=0;index<keys.length;index+=1)deepFreeze(value[keys[index]],seen);return safeFreeze(value)}
function unavailable(code='INVALID_SHIFT_INPUT'){return deepFreeze({status:'unavailable',code,suggestion:null})}
function exactKeys(value,fields){if(!plainRecord(value))return false;const keys=safeObjectKeys(value);if(keys.length!==fields.length)return false;for(let index=0;index<keys.length;index+=1)if(!safeIncludes(fields,keys[index]))return false;return true}
function denseUniqueWeekdays(value){if(!safeArrayIsArray(value)||value.length<1||value.length>7||safeOwnKeys(value).length!==value.length+1)return false;const seen=new SafeSet();for(let index=0;index<value.length;index+=1){if(!safeHasOwn(value,index)||typeof value[index]!=='string'||!safeIncludes(WEEKDAYS,value[index])||safeSetHas(seen,value[index]))return false;safeSetAdd(seen,value[index])}return true}
function canonicalPlan(plan){if(!plainRecord(plan)||typeof plan.id!=='string'||!safeRegexTest(MACHINE_ID,plan.id)||!safeArrayIsArray(plan.weeks)||plan.weeks.length!==4||safeOwnKeys(plan.weeks).length!==5)return null;const sessions=[],ids=new SafeSet();for(let weekIndex=0;weekIndex<4;weekIndex+=1){if(!safeHasOwn(plan.weeks,weekIndex))return null;const week=plan.weeks[weekIndex];if(!plainRecord(week)||week.number!==weekIndex+1||!safeArrayIsArray(week.sessions)||week.sessions.length<1||week.sessions.length>7||safeOwnKeys(week.sessions).length!==week.sessions.length+1)return null;const occupied=new SafeSet();for(let sessionIndex=0;sessionIndex<week.sessions.length;sessionIndex+=1){if(!safeHasOwn(week.sessions,sessionIndex))return null;const item=week.sessions[sessionIndex];if(!plainRecord(item)||typeof item.id!=='string'||!safeRegexTest(MACHINE_ID,item.id)||safeSetHas(ids,item.id)||!safeIncludes(WEEKDAYS,item.weekday)||safeSetHas(occupied,item.weekday)||!safeIncludes(INTENTS,item.intent))return null;safeSetAdd(ids,item.id);safeSetAdd(occupied,item.weekday);safePush(sessions,{id:item.id,weekNumber:weekIndex+1,weekday:item.weekday,intent:item.intent,absolute:weekIndex*7+safeIndexOf(WEEKDAYS,item.weekday)})}}return{id:plan.id,sessions,ids}}
function completedSet(logs,plan){if(!safeArrayIsArray(logs)||logs.length>256||safeOwnKeys(logs).length!==logs.length+1)return null;const completed=new SafeSet();for(let index=0;index<logs.length;index+=1){if(!safeHasOwn(logs,index))return null;const record=logs[index],keys=plainRecord(record)?safeObjectKeys(record):[];if(!plainRecord(record)||keys.length<4||keys.length>LOG_FIELDS.length) return null;for(let keyIndex=0;keyIndex<keys.length;keyIndex+=1)if(!safeIncludes(LOG_FIELDS,keys[keyIndex]))return null;if(record.planId!==plan.id||typeof record.sessionId!=='string'||!safeSetHas(plan.ids,record.sessionId)||record.status!=='completed'||typeof record.completedAt!=='string'||!safeRegexTest(UTC_ISO,record.completedAt)||safeSetHas(completed,record.sessionId))return null;safeSetAdd(completed,record.sessionId)}return completed}
function suggestScheduleShift(raw){
  if(!intrinsicsIntact())return unavailable();const input=clonePureData(raw);if(!input||!exactKeys(input,INPUT_FIELDS)||!plainRecord(input.intake)||!denseUniqueWeekdays(input.intake.weekdays)||!safeNumberIsSafeInteger(input.currentWeekNumber)||input.currentWeekNumber<1||input.currentWeekNumber>4||!safeNumberIsSafeInteger(input.allowedThroughWeekNumber)||input.allowedThroughWeekNumber<input.currentWeekNumber||input.allowedThroughWeekNumber>4||input.allowedThroughWeekNumber>input.currentWeekNumber+1||typeof input.sessionId!=='string')return unavailable();
  const plan=canonicalPlan(input.plan);if(!plan)return unavailable();let source=null;for(let index=0;index<plan.sessions.length;index+=1)if(plan.sessions[index].id===input.sessionId){if(source)return unavailable();source=plan.sessions[index]}if(!source||source.weekNumber!==input.currentWeekNumber)return unavailable();
  const completed=completedSet(input.completedLogs,plan);if(!completed)return unavailable();if(safeSetHas(completed,source.id))return unavailable('SESSION_ALREADY_COMPLETED');
  if(source.weekNumber===4&&source.weekday==='sun')return unavailable('CYCLE_COMPLETE');
  const occupied=new SafeSet(),strength=[];for(let index=0;index<plan.sessions.length;index+=1){const item=plan.sessions[index];if(item.id===source.id)continue;safeSetAdd(occupied,`${item.weekNumber}|${item.weekday}`);if(item.intent==='full_body_strength')safePush(strength,item.absolute)}
  const lastAbsolute=input.allowedThroughWeekNumber*7-1;
  for(let absolute=source.absolute+1;absolute<=lastAbsolute;absolute+=1){const weekNumber=safeMathFloor(absolute/7)+1,weekday=WEEKDAYS[absolute%7];if(!safeIncludes(input.intake.weekdays,weekday)||safeSetHas(occupied,`${weekNumber}|${weekday}`))continue;if(source.intent==='full_body_strength'){let safe=true;for(let index=0;index<strength.length;index+=1)if(safeMathAbs(absolute-strength[index])<2){safe=false;break}if(!safe)continue}return deepFreeze({status:'available',code:'SCHEDULE_SHIFT_AVAILABLE',suggestion:{planId:plan.id,sessionId:source.id,intent:source.intent,from:{weekNumber:source.weekNumber,weekday:source.weekday},to:{weekNumber,weekday},displayOnly:true}})}
  return unavailable('NO_SAFE_SHIFT_DAY');
}
return safeFreeze({suggestScheduleShift});
});
