const {test,expect}=require('@playwright/test');
const gymEquipment=['stable_chair','exercise_mat','leg_press_machine','leg_curl_machine','chest_press_machine','seated_row_machine','resistance_band','cable_machine','elliptical_trainer','treadmill'];
const safe={boundaryAccepted:true,age:30,pregnancyPostpartum:'no',goal:'habit',activityDays:'3',walkCapacity:'20_40',strengthExperience:'some',trainingBreak:'no',daysPerWeek:'2',sessionMinutes:'30',weekdays:['mon','thu'],gymOftenUnavailable:'no',setting:'gym',equipment:gymEquipment,allowSettingSwap:'no',painAreas:['none'],painTrend:'none',acuteInjury:'no',unableToBearWeight:'no',visibleSwelling:'no',dailyActivityLimited:'no',chairStand:'yes',walkTenMinutes:'yes',chestSymptoms:'no',exertionalDizziness:'no',unexplainedFainting:'no',restingShortnessOfBreath:'no',unresolvedConcussion:'no',doctorRestriction:'none',recentSurgery:'no',complexCondition:'no',uncontrolledBloodPressure:'no',cardioPreference:'none',cardioAvoid:'none',avoidMovements:[],avoidEquipment:[],trackingItems:['completion'],sessionPreference:'short_frequent',musicEnabled:'no'};
async function setupActive(page){await page.goto('/index.html');await page.evaluate(()=>{localStorage.clear();sessionStorage.clear()});await page.reload();await page.getByRole('button',{name:/生成我的4周计划/}).click();await page.evaluate(data=>{for(const[key,value]of Object.entries(data))Move28.onboardingController.setField(key,value);Move28.onboardingController.goTo(9)},safe);await page.locator('input[name="finalConfirmed"]').check();await page.getByRole('button',{name:/确认并保存结果/}).click();await page.getByRole('button',{name:'完成，返回首页'}).click();await page.evaluate(()=>{const state=Move28.storage.loadState();Move28.storage.approvePlanReview({reviewerId:'pilot-reviewer',planId:state.plan.id,intakeRevision:state.intakeRevision})});await page.reload()}
async function openReview(page){await page.getByRole('button',{name:'第1周复盘'}).click();await expect(page.getByRole('heading',{name:'每周复盘'})).toBeVisible()}

test('weekly-review demo和pending计划不显示复盘入口',async({page})=>{await page.goto('/index.html');await page.evaluate(()=>localStorage.clear());await page.reload();await expect(page.locator('.weekly-review-open')).toHaveCount(0);await page.getByRole('button',{name:/生成我的4周计划/}).click();await page.evaluate(data=>{for(const[key,value]of Object.entries(data))Move28.onboardingController.setField(key,value);Move28.onboardingController.goTo(9)},safe);await page.locator('input[name="finalConfirmed"]').check();await page.getByRole('button',{name:/确认并保存结果/}).click();await page.getByRole('button',{name:'完成，返回首页'}).click();await expect(page.locator('.weekly-review-open')).toHaveCount(0)});

test('weekly-review 提交合适反馈只生成建议，保持原计划记录rejected',async({page})=>{await setupActive(page);const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('move28-pilot-v1')).plan);await openReview(page);await page.getByRole('button',{name:'查看复盘建议'}).click();await expect(page.getByText('原计划',{exact:true})).toBeVisible();await expect(page.getByText('建议变化',{exact:true})).toBeVisible();await expect(page.getByText('原因',{exact:true})).toBeVisible();const pending=await page.evaluate(()=>JSON.parse(localStorage.getItem('move28-pilot-v1')));expect(pending.plan).toEqual(before);expect(pending.weeklyReviews[0].decision).toBe('pending');await page.getByRole('button',{name:'保持原计划'}).click();await expect(page.getByRole('heading',{name:'已保持原计划'})).toBeVisible();const rejected=await page.evaluate(()=>JSON.parse(localStorage.getItem('move28-pilot-v1')));expect(rejected.plan.status).toBe('active');expect(rejected.weeklyReviews[0].decision).toBe('rejected')});

test('weekly-review 关闭或刷新建议不会自动接受，并可继续决定',async({page})=>{await setupActive(page);await openReview(page);await page.locator('select[name="difficulty"]').selectOption('too_hard');await page.getByRole('button',{name:'查看复盘建议'}).click();await page.getByRole('button',{name:'关闭周复盘'}).click();let state=await page.evaluate(()=>JSON.parse(localStorage.getItem('move28-pilot-v1')));expect(state.plan.status).toBe('active');expect(state.weeklyReviews[0].decision).toBe('pending');await page.reload();await page.getByRole('button',{name:'继续决定'}).click();await expect(page.getByText(/只调整：重复次数/)).toBeVisible();state=await page.evaluate(()=>JSON.parse(localStorage.getItem('move28-pilot-v1')));expect(state.weeklyReviews[0].decision).toBe('pending')});

test('weekly-review 过难只调整一个变量，用户确认后等待人工复核',async({page})=>{await setupActive(page);await openReview(page);await page.locator('select[name="completionReason"]').selectOption('difficulty');await page.locator('select[name="difficulty"]').selectOption('too_hard');await page.getByRole('button',{name:'查看复盘建议'}).click();await expect(page.getByText(/只调整：重复次数/)).toBeVisible();await page.getByRole('button',{name:'确认调整'}).click();await expect(page.getByRole('heading',{name:/等待人工复核/})).toBeVisible();const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('move28-pilot-v1')));expect(state.plan.status).toBe('pending_review');expect(state.plan.review).toBeNull();expect(state.weeklyReviews[0].decision).toBe('accepted');await expect(page.getByRole('button',{name:'开始本节训练'})).toHaveCount(0);await expect(page.locator('.weekly-review-open')).toHaveCount(0);await page.evaluate(()=>{const state=Move28.storage.loadState();Move28.storage.approvePlanReview({reviewerId:'pilot-reviewer',planId:state.plan.id,intakeRevision:state.intakeRevision})});await page.reload();await expect(page.getByRole('button',{name:'第2周复盘'})).toBeVisible();await expect(page.getByRole('button',{name:'第1周复盘'})).toHaveCount(0)});

test('weekly-review 新发疼痛立即使计划失效且进入第6步重筛',async({page})=>{await setupActive(page);await openReview(page);await page.locator('select[name="painStatus"]').selectOption('new');await page.locator('select[name="painArea"]').selectOption('knee');await page.getByRole('button',{name:'查看复盘建议'}).click();await expect(page.getByRole('heading',{name:'请先重新完成安全筛查'})).toBeVisible();const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('move28-pilot-v1')));expect(state.plan.status).toBe('stale');expect(state.plan.staleReason).toBe('weekly_pain_rescreen');expect(state.weeklyReviews[0].decision).toBe('rescreen');await page.getByRole('button',{name:'进入重新筛查'}).click();await expect(page.locator('#onboardingView')).toHaveClass(/open/);expect(await page.evaluate(()=>Move28.onboardingController.getState().step)).toBe(6)});

test('weekly-review 本地保存失败不显示成功并可原页重试',async({page})=>{await setupActive(page);await openReview(page);await page.evaluate(()=>{Storage.prototype.setItem=()=>{throw new Error('SECRET')}});await page.getByRole('button',{name:'查看复盘建议'}).click();await expect(page.getByText('本机保存失败，复盘尚未提交，请重试。')).toBeVisible();await expect(page.getByRole('button',{name:'查看复盘建议'})).toBeVisible();await expect(page.getByText(/SECRET/)).toHaveCount(0)});

test('weekly-review 390×844无横向溢出且提交按钮可触达',async({page},testInfo)=>{test.skip(testInfo.project.name!=='mobile');await setupActive(page);await openReview(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);await expect(page.getByRole('button',{name:'查看复盘建议'})).toBeVisible()});
