const {test,expect}=require('@playwright/test');
const {resetHttp,completeOnboarding,approvePendingPlan,completeGuideActions,answerSafeReadiness}=require('./helpers/pilot-flow.cjs');
async function setupActive(page){await resetHttp(page);await completeOnboarding(page);await page.getByRole('button',{name:'完成，返回首页'}).click();await approvePendingPlan(page)}
async function openReview(page){await page.getByRole('button',{name:'第1周复盘'}).click();await expect(page.getByRole('heading',{name:'每周复盘'})).toBeVisible()}
async function finishFirstWorkout(page){await page.getByRole('button',{name:'开始今天训练'}).click();await answerSafeReadiness(page);await page.getByRole('button',{name:'检查今天状态'}).click();await page.getByRole('button',{name:'按原计划继续'}).click();await page.getByRole('button',{name:'开始本节',exact:true}).click();await completeGuideActions(page);await expect(page.getByRole('heading',{name:'这节训练感觉如何？'})).toBeVisible()}

test('weekly-review demo和pending计划不显示复盘入口',async({page})=>{await resetHttp(page);await expect(page.locator('.weekly-review-open')).toHaveCount(0);await completeOnboarding(page);await page.getByRole('button',{name:'完成，返回首页'}).click();await expect(page.locator('.weekly-review-open')).toHaveCount(0)});

test('weekly-review 提交合适反馈只生成建议，保持原计划记录rejected',async({page})=>{await setupActive(page);const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('move28-pilot-v1')).plan);await openReview(page);await page.getByRole('button',{name:'查看复盘建议'}).click();await expect(page.getByText('原计划',{exact:true})).toBeVisible();await expect(page.getByText('建议变化',{exact:true})).toBeVisible();await expect(page.getByText('原因',{exact:true})).toBeVisible();const pending=await page.evaluate(()=>JSON.parse(localStorage.getItem('move28-pilot-v1')));expect(pending.plan).toEqual(before);expect(pending.weeklyReviews[0].decision).toBe('pending');await page.getByRole('button',{name:'保持原计划'}).click();await expect(page.getByRole('heading',{name:'已保持原计划'})).toBeVisible();const rejected=await page.evaluate(()=>JSON.parse(localStorage.getItem('move28-pilot-v1')));expect(rejected.plan.status).toBe('active');expect(rejected.weeklyReviews[0].decision).toBe('rejected')});

test('weekly-review 关闭或刷新建议不会自动接受，并可继续决定',async({page})=>{await setupActive(page);await openReview(page);await page.locator('select[name="difficulty"]').selectOption('too_hard');await page.getByRole('button',{name:'查看复盘建议'}).click();await page.getByRole('button',{name:'关闭周复盘'}).click();let state=await page.evaluate(()=>JSON.parse(localStorage.getItem('move28-pilot-v1')));expect(state.plan.status).toBe('active');expect(state.weeklyReviews[0].decision).toBe('pending');await page.reload();await page.getByRole('button',{name:'继续决定'}).click();await expect(page.getByText(/只调整：重复次数/)).toBeVisible();state=await page.evaluate(()=>JSON.parse(localStorage.getItem('move28-pilot-v1')));expect(state.weeklyReviews[0].decision).toBe('pending')});

test('weekly-review 过难只调整一个变量，用户确认后等待计划确认',async({page})=>{await setupActive(page);await openReview(page);await page.locator('select[name="completionReason"]').selectOption('difficulty');await page.locator('select[name="difficulty"]').selectOption('too_hard');await page.getByRole('button',{name:'查看复盘建议'}).click();await expect(page.getByText(/只调整：重复次数/)).toBeVisible();await page.getByRole('button',{name:'确认调整'}).click();await expect(page.getByRole('heading',{name:'调整已提交，等待确认'})).toBeVisible();const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('move28-pilot-v1')));expect(state.plan.status).toBe('pending_review');expect(state.plan.review).toBeNull();expect(state.weeklyReviews[0].decision).toBe('accepted');await expect(page.getByRole('button',{name:'开始今天训练'})).toHaveCount(0);await expect(page.locator('.weekly-review-open')).toHaveCount(0);await page.evaluate(()=>{const state=Move28.storage.loadState();Move28.storage.approvePlanReview({reviewerId:'pilot-reviewer',planId:state.plan.id,intakeRevision:state.intakeRevision})});await page.reload();await expect(page.getByRole('button',{name:'第2周复盘'})).toBeVisible();await expect(page.getByRole('button',{name:'第1周复盘'})).toHaveCount(0)});

test('weekly-review 合法减少下一周训练节数后解释显示范围',async({page})=>{await setupActive(page);await openReview(page);await page.locator('select[name="completionReason"]').selectOption('time');await page.locator('select[name="nextWeekTime"]').selectOption('less');await page.getByRole('button',{name:'查看复盘建议'}).click();await page.getByRole('button',{name:'确认调整'}).click();let state=await page.evaluate(()=>JSON.parse(localStorage.getItem('move28-pilot-v1')));expect(state.plan.status).toBe('pending_review');expect(state.weeklyReviews[0].proposal.variable).toBe('session_count');await page.evaluate(()=>{const state=Move28.storage.loadState();Move28.storage.approvePlanReview({reviewerId:'pilot-reviewer',planId:state.plan.id,intakeRevision:state.intakeRevision})});await page.reload();await page.locator('.plan-explanation summary').click();await expect(page.locator('.plan-explanation')).toContainText('每周1–2节');state=await page.evaluate(()=>JSON.parse(localStorage.getItem('move28-pilot-v1')));expect(state.plan.weeks.map(week=>week.sessions.length)).toEqual([2,1,2,2])});

test('weekly-review 新发疼痛立即使计划失效且进入第6步重筛',async({page})=>{await setupActive(page);await openReview(page);await page.locator('select[name="painStatus"]').selectOption('new');await page.locator('select[name="painArea"]').selectOption('knee');await page.getByRole('button',{name:'查看复盘建议'}).click();await expect(page.getByRole('heading',{name:'请先重新完成安全筛查'})).toBeVisible();const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('move28-pilot-v1')));expect(state.plan.status).toBe('stale');expect(state.plan.staleReason).toBe('weekly_pain_rescreen');expect(state.weeklyReviews[0].decision).toBe('rescreen');await page.getByRole('button',{name:'进入重新筛查'}).click();await expect(page.locator('#onboardingView')).toHaveClass(/open/);expect(await page.evaluate(()=>Move28.onboardingController.getState().step)).toBe(6)});

test('weekly-review 本地保存失败不显示成功并可原页重试',async({page})=>{await setupActive(page);await openReview(page);await page.evaluate(()=>{Storage.prototype.setItem=()=>{throw new Error('SECRET')}});await page.getByRole('button',{name:'查看复盘建议'}).click();await expect(page.getByText('本机保存失败，复盘尚未提交，请重试。')).toBeVisible();await expect(page.getByRole('button',{name:'查看复盘建议'})).toBeVisible();await expect(page.getByText(/SECRET/)).toHaveCount(0)});

test('weekly-review 390×844无横向溢出且提交按钮可触达',async({page},testInfo)=>{test.skip(testInfo.project.name!=='mobile');await setupActive(page);await openReview(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);await expect(page.getByRole('button',{name:'查看复盘建议'})).toBeVisible()});

test('完成训练后显示固定四选一，appropriate 保存绑定反馈并关闭且刷新保留',async({page})=>{await setupActive(page);await finishFirstWorkout(page);await expect(page.locator('#guideBody button')).toHaveCount(4);await expect(page.locator('#guideBody input,#guideBody textarea,#guideBody select')).toHaveCount(0);await page.getByRole('button',{name:'刚刚好'}).click();await expect(page.locator('#guideModal')).toHaveAttribute('aria-hidden','true');let state=await page.evaluate(()=>JSON.parse(localStorage.getItem('move28-pilot-v1'))),record=Object.values(state.logs).find(item=>item.feedbackCode==='appropriate');expect(record).toMatchObject({planId:state.plan.id,capabilityRevision:state.capabilityRevision,feedbackCode:'appropriate'});expect(record.feedbackAt).toMatch(/Z$/);await page.reload();state=await page.evaluate(()=>JSON.parse(localStorage.getItem('move28-pilot-v1')));expect(Object.values(state.logs).filter(item=>item.feedbackCode==='appropriate')).toHaveLength(1)});
test('反馈保存失败保留四选一可重试且不重复完成记录',async({page})=>{await setupActive(page);await finishFirstWorkout(page);const summaryBefore=await page.locator('.guide-completion').textContent();await page.evaluate(()=>{window.__feedbackSetItem=Storage.prototype.setItem;Storage.prototype.setItem=()=>{throw new Error('BLOCKED')}});await page.getByRole('button',{name:'太难了'}).click();await expect(page.getByText('反馈尚未保存，请检查本机存储后重试。')).toBeVisible();await expect(page.getByRole('heading',{name:'这节训练感觉如何？'})).toBeVisible();await expect(page.locator('.guide-completion')).toHaveText(summaryBefore);await page.evaluate(()=>{Storage.prototype.setItem=window.__feedbackSetItem;delete window.__feedbackSetItem});await page.getByRole('button',{name:'太难了'}).click();await expect(page.locator('#guideModal')).toHaveAttribute('aria-hidden','true');const records=await page.evaluate(()=>Object.values(JSON.parse(localStorage.getItem('move28-pilot-v1')).logs).filter(item=>item.status==='completed'));expect(records).toHaveLength(1);expect(records[0].feedbackCode).toBe('too_hard')});
test('训练后 pain 反馈原子 stale 并立即进入第6步重筛',async({page})=>{await setupActive(page);await finishFirstWorkout(page);await page.getByRole('button',{name:'出现疼痛'}).click();await expect(page.locator('#guideModal')).toHaveAttribute('aria-hidden','true');await expect(page.locator('#onboardingView')).toHaveClass(/open/);expect(await page.evaluate(()=>Move28.onboardingController.getState().step)).toBe(6);const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('move28-pilot-v1'))),record=Object.values(state.logs).find(item=>item.feedbackCode==='pain');expect(state.plan.status).toBe('stale');expect(state.plan.staleReason).toBe('workout_feedback_pain');expect(state.plan.staleAt).toBe(record.feedbackAt)});
test('pain 已写入但读回确认失败时同码重试恢复且只写一次',async({page})=>{await setupActive(page);await finishFirstWorkout(page);await page.evaluate(()=>{window.__feedbackOriginalSet=Storage.prototype.setItem;window.__feedbackOriginalGet=Storage.prototype.getItem;window.__feedbackWrites=0;window.__feedbackFailRead=false;Storage.prototype.setItem=function(key,value){window.__feedbackOriginalSet.call(this,key,value);window.__feedbackWrites+=1;window.__feedbackFailRead=true};Storage.prototype.getItem=function(key){if(window.__feedbackFailRead){window.__feedbackFailRead=false;throw new Error('READ_AFTER_WRITE')}return window.__feedbackOriginalGet.call(this,key)}});await page.getByRole('button',{name:'出现疼痛'}).click();await expect(page.getByText('反馈尚未保存，请检查本机存储后重试。')).toBeVisible();let state=await page.evaluate(()=>JSON.parse(window.__feedbackOriginalGet.call(localStorage,'move28-pilot-v1')));expect(state.plan.status).toBe('stale');expect(Object.values(state.logs).find(item=>item.feedbackCode==='pain')).toBeTruthy();await page.getByRole('button',{name:'出现疼痛'}).click();await expect(page.locator('#guideModal')).toHaveAttribute('aria-hidden','true');await expect(page.locator('#onboardingView')).toHaveClass(/open/);expect(await page.evaluate(()=>Move28.onboardingController.getState().step)).toBe(6);expect(await page.evaluate(()=>window.__feedbackWrites)).toBe(1);await page.evaluate(()=>{Storage.prototype.setItem=window.__feedbackOriginalSet;Storage.prototype.getItem=window.__feedbackOriginalGet})});
test('绑定的 too_hard 反馈覆盖UI合适选择并真正影响周复盘',async({page})=>{await setupActive(page);await finishFirstWorkout(page);await page.getByRole('button',{name:'太难了'}).click();await openReview(page);await expect(page.getByText(/本周已记录 1\/2 节训练反馈/)).toBeVisible();await expect(page.locator('#weeklyReviewView')).not.toContainText('%');await page.getByRole('button',{name:'查看复盘建议'}).click();await expect(page.getByText(/只调整：重复次数/)).toBeVisible();const record=await page.evaluate(()=>JSON.parse(localStorage.getItem('move28-pilot-v1')).weeklyReviews[0]);expect(record.answers.difficulty).toBe('too_hard');expect(record.proposal.reasonCode).toBe('difficulty_reduced')});
