(function(root,factory){
const isCommonJS=typeof module==='object'&&module.exports;
const Move28=isCommonJS?require('../namespace.js'):(root.Move28=root.Move28||{});
if(isCommonJS){require('../data/legacy-demo-plan.js');require('../data/tracker-fields.js')}
const api=factory(root,Move28);
if(isCommonJS)module.exports=api;
})(globalThis,function(root,Move28){
'use strict';
const DATA=Move28.data.legacyDemoPlan;
const TRACKER_FIELDS=Move28.data.trackerFields;
const state=Move28.state;
const {$,$$,esc,localDate,storage}=Move28.utils;
function dayClass(t){return /力量/.test(t)?'strength':/有氧/.test(t)?'cardio':'recovery'}
function progress(){const done=Object.values(state.tracker).filter(r=>['已完成','部分完成'].includes(r['完成状态'])).length;return{done,pct:Math.round(done/28*100)}}
function renderToday(){const d=DATA.days[state.currentDay-1],p=progress();$('#todayCard').innerHTML=`<div class="today-day"><span>DAY / 第${d.week}周</span><strong>${String(d.day).padStart(2,'0')}</strong></div><div class="today-content"><div class="today-top"><span class="chip">${esc(d.weekday)} · ${esc(d.place)}</span><span class="chip">${esc(d.duration)}</span></div><h3>${esc(d.type)}</h3><div class="today-grid"><div class="today-block"><div class="label">热身与力量</div><div class="today-value">${esc(d.strength)}</div></div><div class="today-block"><div class="label">有氧 / 步行</div><div class="today-value">${esc(d.cardio)}</div></div><div class="today-block"><div class="label">强度</div><div class="today-value">力量RPE 5–6<br>有氧RPE 4–5</div></div></div><div class="progress-wrap"><div class="progress-line"><i style="width:${p.pct}%"></i></div><div class="progress-text">已记录完成 ${p.done}/28 天 · ${p.pct}%</div></div><div class="day-controls"><button class="btn" onclick="moveDay(-1)">← 前一天</button><button class="btn primary today-start" onclick="openGuide(${d.day})">▶ 一步一步带我练</button><button class="btn" onclick="openTrack(${d.day})">快速记录</button><button class="btn" onclick="moveDay(1)">后一天 →</button></div><span class="tiny-help">第一次训练直接点绿色按钮；页面会逐步告诉你做什么。</span></div>`}
Move28.moveDay=n=>{state.currentDay=Math.min(28,Math.max(1,state.currentDay+n));storage.setItem('move28-current-day',state.currentDay);renderToday()};
function renderWeeks(){$('#weekTabs').innerHTML=DATA.weeks.map(w=>`<button class="tab ${w.week===state.currentWeek?'active':''}" onclick="pickWeek(${w.week})">第${w.week}周</button>`).join('');const w=DATA.weeks[state.currentWeek-1];$('#weekView').innerHTML=`<div class="week-focus"><span>本周重点</span>${esc(w.focus)}</div><div class="days-grid">${w.days.map(d=>`<article class="day-card ${dayClass(d.type)}"><div class="num">${d.day}</div><h3>${esc(d.weekday)}</h3><div class="type">${esc(d.type)}</div><dl><dt>热身与力量</dt><dd>${esc(d.strength)}</dd><dt>有氧／步行</dt><dd>${esc(d.cardio)}</dd><dt>地点与时长</dt><dd>${esc(d.place)} · ${esc(d.duration)}</dd></dl></article>`).join('')}</div>`}
Move28.pickWeek=n=>{state.currentWeek=n;renderWeeks()};
function renderExercises(){const groups=['全部','力量A','力量B','有氧C'];$('#exerciseTabs').innerHTML=groups.map(g=>`<button class="tab ${g===state.exerciseFilter?'active':''}" onclick="pickExercise('${g}')">${g}</button>`).join('');const list=DATA.exercises.filter(e=>state.exerciseFilter==='全部'||e.groups.includes(state.exerciseFilter));$('#exerciseGrid').innerHTML=list.map(e=>`<article class="exercise"><div class="exercise-media"><img src="${esc(e.gif)}" alt="${esc(e.name)}动作GIF"></div><div class="exercise-body"><h3>${esc(e.name)}</h3><div class="tags">${e.groups.map(g=>`<span class="tag">${g}</span>`).join('')}</div><details class="detail" open><summary>起始姿势</summary><p>${esc(e.start)}</p></details><details class="detail"><summary>动作步骤</summary><p>${esc(e.steps)}</p></details><details class="detail"><summary>呼吸与节奏</summary><p>${esc(e.breath)}</p></details><details class="detail"><summary>常见错误</summary><p>${esc(e.errors)}</p></details><details class="detail"><summary>安全保护要点</summary><p class="danger-text">${esc(e.safety)}</p></details></div></article>`).join('')}
Move28.pickExercise=g=>{state.exerciseFilter=g;renderExercises()};
const inputSkip=new Set(['天数','周次','星期','计划训练']);
function fieldType(label){if(/日期$/.test(label))return'date';if(/备注|异常症状/.test(label))return'textarea';if(/时间/.test(label))return'time';if(/完成状态/.test(label))return'status';if(/精力/.test(label))return'scale';return'number'}
function renderDayList(){$('#dayList').innerHTML=DATA.days.map(d=>`<button class="day-pick ${d.day===state.trackDay?'active':''}" onclick="selectTrackDay(${d.day})">${String(d.day).padStart(2,'0')} · ${d.weekday}</button>`).join('')}
const quickTrackLabels=new Set(['日期','完成状态','步数','有氧(分钟)','力量(分钟)','睡眠(小时)']);
function buildTrackField(h,rec){const val=rec[h.label]??(h.label==='日期'&&state.trackDay===state.currentDay?localDate():''),type=fieldType(h.label),wide=/备注|异常症状/.test(h.label)||type==='status'?' wide':'';let ctrl;if(type==='textarea')ctrl=`<textarea data-label="${esc(h.label)}" placeholder="${esc(h.help)}">${esc(val)}</textarea>`;else if(type==='status'){const states=['未填写','已完成','部分完成','休息','因不适暂停'];ctrl=`<input type="hidden" data-label="${esc(h.label)}" value="${esc(val||'未填写')}"><div class="quick-status">${states.map(x=>`<button type="button" class="status-choice ${x===(val||'未填写')?'active':''}" onclick="setStatus('${x}',this)">${x}</button>`).join('')}</div>`}else if(type==='scale')ctrl=`<select data-label="${esc(h.label)}"><option value=""></option>${[1,2,3,4,5].map(x=>`<option ${String(x)===String(val)?'selected':''}>${x}</option>`).join('')}</select>`;else ctrl=`<input data-label="${esc(h.label)}" type="${type}" value="${esc(val)}" step="any" placeholder="${esc(h.help)}">`;return`<div class="field${wide}"><label title="${esc(h.help)}">${esc(h.label)}</label>${ctrl}</div>`}
function renderForm(){const d=DATA.days[state.trackDay-1],rec=state.tracker[state.trackDay]||{},fields=TRACKER_FIELDS.filter(h=>!inputSkip.has(h.label)),quick=fields.filter(h=>quickTrackLabels.has(h.label)),advanced=fields.filter(h=>!quickTrackLabels.has(h.label)),hasAdvanced=advanced.some(h=>String(rec[h.label]??'').trim());$('#trackTitle').textContent=`第${state.trackDay}天 · ${d.weekday} · ${d.type}`;$('#trackForm').innerHTML=`<div class="form-grid quick-grid">${quick.map(h=>buildTrackField(h,rec)).join('')}</div><details class="advanced-panel" ${hasAdvanced?'open':''}><summary>高级记录 <span>体重／血压／生活习惯／疼痛（可选）</span></summary><div class="form-grid advanced-grid">${advanced.map(h=>buildTrackField(h,rec)).join('')}</div></details>`}
Move28.setStatus=(value,button)=>{const box=button.closest('.field');box.querySelector('[data-label="完成状态"]').value=value;box.querySelectorAll('.status-choice').forEach(x=>x.classList.toggle('active',x===button))};
Move28.selectTrackDay=n=>{state.trackDay=n;renderDayList();renderForm()};Move28.openTrack=n=>{state.trackDay=n;renderDayList();renderForm();root.location.hash='tracker';setTimeout(()=>$('#trackForm [data-label="完成状态"]')?.closest('.field')?.scrollIntoView({block:'center'}),350)};
function showToast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
function saveTrack(){const d={};$$('#trackForm [data-label]').forEach(el=>d[el.dataset.label]=el.value);state.tracker[state.trackDay]=d;storage.setItem(state.storeKey,JSON.stringify(state.tracker));renderOverview();renderToday();$('#saveBtn').textContent='已保存 ✓';showToast(`第${state.trackDay}天已保存到当前浏览器`);setTimeout(()=>$('#saveBtn').textContent='保存今天 ✓',1400)}
function renderOverview(){$('#overviewBody').innerHTML=DATA.days.map(d=>{const r=state.tracker[d.day]||{};return`<tr><td>${d.day}</td><td>${esc(r['日期']||'')}</td><td>${esc(d.type)}</td><td>${esc(r['完成状态']||'未填写')}</td><td>${esc(r['晨起体重(kg)']||'')}</td><td>${esc((r['收缩压(mmHg)']||'')+(r['舒张压(mmHg)']?'/'+r['舒张压(mmHg)']:''))}</td><td>${esc(r['步数']||'')}</td><td>${esc(r['睡眠(小时)']||'')}</td><td>${esc([r['肩部痛(0-10)'],r['膝痛(0-10)'],r['腰痛(0-10)']].map(x=>x||'-').join('/'))}</td></tr>`}).join('')}
function exportCSV(){const hs=['天数','周次','星期','计划训练',...TRACKER_FIELDS.filter(h=>!inputSkip.has(h.label)).map(h=>h.label)];const rows=[hs,...DATA.days.map(d=>{const r=state.tracker[d.day]||{};return[d.day,d.week,d.weekday,d.type,...hs.slice(4).map(h=>r[h]||'')]})];const csv='\ufeff'+rows.map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join(String.fromCharCode(13,10));const a=root.document.createElement('a');a.href=root.URL.createObjectURL(new root.Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='28天健身追踪.csv';a.click();root.URL.revokeObjectURL(a.href);showToast('CSV备份已生成')}
function clearTrack(){const b=$('#clearBtn');if(!state.clearArmed){state.clearArmed=true;b.textContent='再点一次确认';showToast(`再次点击即可清空第${state.trackDay}天`);clearTimeout(state.clearArmTimer);state.clearArmTimer=setTimeout(()=>{state.clearArmed=false;b.textContent='清空这天'},3000);return}state.clearArmed=false;clearTimeout(state.clearArmTimer);delete state.tracker[state.trackDay];storage.setItem(state.storeKey,JSON.stringify(state.tracker));renderForm();renderOverview();renderToday();b.textContent='清空这天';showToast(`第${state.trackDay}天记录已清空`)}
function renderSafety(){$('#safetyGrid').innerHTML=DATA.safety.map(x=>`<article class="safety-card"><h3>${esc(x.title)}</h3><div>${esc(x.text)}</div></article>`).join('')}
function reveal(){const io=new root.IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08});$$('.reveal').forEach(x=>io.observe(x))}
const ui={renderToday,renderWeeks,renderExercises,renderDayList,renderForm,renderOverview,renderSafety,reveal,saveTrack,exportCSV,clearTrack,showToast};
Object.assign(Move28.ui||{},ui);
const actions={moveDay:Move28.moveDay,pickWeek:Move28.pickWeek,pickExercise:Move28.pickExercise,setStatus:Move28.setStatus,selectTrackDay:Move28.selectTrackDay,openTrack:Move28.openTrack};
if(root.window===root)for(const name of Object.keys(actions))root[name]=actions[name];
return Object.assign({},ui,actions);
});
