(function(Move28){
const DATA=Move28.data.legacyDemoPlan;
const state=Move28.state;
const {$,esc}=Move28.utils;
const MUSIC={warmup:{src:'assets/audio/warmup-rising-forest.mp3',title:'Rising Forest',author:'Diego Nava · 热身'},strength:{src:'assets/audio/strength-deep-urban.mp3',title:'Deep Urban',author:'Eugenio Mininni · 力量'},cardio:{src:'assets/audio/cardio-techno-fest-vibes.mp3',title:'Techno Fest Vibes',author:'Alejandro Magaña (A. M.) · 有氧'},recovery:{src:'assets/audio/recovery-summer-dream.mp3',title:'Summer Dream',author:'Eugenio Mininni · 放松'}};
const exerciseByName=name=>DATA.exercises.find(e=>e.name===name);
function actionStep(name,dose,phase,music){const exercise=exerciseByName(name);return{title:name,dose,phase,music,exercise}}
function cardioGuideSteps(d){const primary=d.cardio.split('；')[0].replace(/，(?:可拆|可分|中途可).*/,''),parts=primary.split('＋').map(x=>x.trim()).filter(Boolean);return parts.map(part=>{const name=part.includes('椭圆机')?'椭圆机／交叉训练机':'平地慢走';return actionStep(name,part,name.startsWith('椭圆机')?'低冲击有氧':'平地步行','cardio')})}
function guideStepsFor(d){const isStrength=/力量[AB]/.test(d.type),group=d.type.match(/力量[AB]/)?.[0],excluded=new Set(['坐姿抬腿','脚踝绕环','椭圆机／交叉训练机','平地慢走','大腿后侧拉伸','小腿拉伸']),moves=isStrength?DATA.exercises.filter(e=>e.groups.includes(group)&&!excluded.has(e.name)).map(e=>e.name):[],steps=[{title:'先确认今天适合训练',copy:'花10秒检查身体状态。任何停止信号都比完成计划更重要。',callout:'如果今天明显不舒服，直接退出跟练并休息，不需要硬撑。',safety:true,music:'warmup'}];if(isStrength){steps.push(actionStep('坐姿抬腿','左右交替各10次 · 轻松完成','热身 1 / 3','warmup'),actionStep('脚踝绕环','每侧顺时针10次＋逆时针10次','热身 2 / 3','warmup'),actionStep('椭圆机／交叉训练机','最低阻力慢速8～10分钟','热身 3 / 3','warmup'),...moves.map(name=>actionStep(name,'2组 × 8～12次 · 组间休息60～90秒 · RPE 5–6',group,'strength')))}steps.push(...cardioGuideSteps(d),actionStep('大腿后侧拉伸','每侧轻柔保持20秒','放松 1 / 2','recovery'),actionStep('小腿拉伸','每侧轻柔保持20秒','放松 2 / 2','recovery'),{title:'完成今天',copy:'如果没有异常不适，就可以完成打卡。页面会自动记录今天，并带你去快速记录。',callout:'如出现胸痛、眩晕、异常气短、心悸或尖锐关节痛，应退出跟练并及时处理。',music:'recovery'});return steps}
const workoutAudio=$('#workoutAudio');
function updateMusicUI(){const m=MUSIC[state.musicKey],playing=!workoutAudio.paused;$('#musicDock').classList.toggle('paused',!playing);$('#musicToggle').textContent=playing?'Ⅱ':'▶';$('#musicToggle').setAttribute('aria-label',playing?'暂停音乐':'播放音乐');$('#musicTitle').textContent=m?m.title:'准备播放';$('#musicCredit').textContent=m?`${m.author} · Mixkit`:'按训练环节自动切换'}
function syncGuideMusic(key,allowPlay=true){const m=MUSIC[key];if(!m)return;if(state.musicKey!==key){state.musicKey=key;workoutAudio.pause();workoutAudio.src=m.src}workoutAudio.volume=state.musicVolume;$('#musicVolume').value=Math.round(state.musicVolume*100);if(state.musicEnabled&&allowPlay)workoutAudio.play().catch(err=>{if(err.name!=='AbortError'){state.musicEnabled=false;localStorage.setItem('move28-music-enabled','0');updateMusicUI()}});updateMusicUI()}
Move28.toggleWorkoutMusic=()=>{if(workoutAudio.paused){state.musicEnabled=true;localStorage.setItem('move28-music-enabled','1');workoutAudio.play().catch(()=>Move28.ui.showToast('请再点一次播放音乐'))}else{state.musicEnabled=false;localStorage.setItem('move28-music-enabled','0');workoutAudio.pause()}updateMusicUI()};
Move28.setWorkoutVolume=value=>{state.musicVolume=Math.max(0,Math.min(1,Number(value)/100));workoutAudio.volume=state.musicVolume;localStorage.setItem('move28-music-volume',String(Math.round(state.musicVolume*100)))};
function renderGuide(){const s=state.guideSteps[state.guideStep],total=state.guideSteps.length,e=s.exercise;syncGuideMusic(s.music,true);$('#guideEyebrow').textContent=`STEP ${state.guideStep+1} / ${total}`;$('#guideTitle').textContent=`第${state.guideDay}天 · ${DATA.days[state.guideDay-1].type}`;$('#guideBar').style.width=`${(state.guideStep+1)/total*100}%`;$('#guideBody').innerHTML=e?`<div class="guide-action"><figure class="guide-demo"><img src="assets/gifs/${encodeURIComponent(e.gif)}" alt="${esc(e.name)}动作示范GIF"></figure><div class="guide-instruction"><span class="guide-phase">${esc(s.phase)}</span><h3>${esc(s.title)}</h3><div class="guide-dose">${esc(s.dose)}</div><div class="guide-cues"><div class="guide-cue"><b>动作要领</b>${esc(e.steps)}</div><div class="guide-cue"><b>呼吸节奏</b>${esc(e.breath)}</div></div><div class="guide-one-note">完成当前动作后，点击下方按钮直接进入下一项。</div></div></div>`:`<div class="guide-step-num">${String(state.guideStep+1).padStart(2,'0')}</div><h3>${esc(s.title)}</h3><div class="guide-copy">${esc(s.copy)}</div>${s.callout?`<div class="guide-callout">${esc(s.callout)}</div>`:''}${s.safety?`<div class="guide-safety"><div><b>可以开始</b>精神和平常相近，呼吸正常，无明显疼痛。</div><div><b>今天停止</b>胸痛、眩晕、心悸、异常气短或尖锐痛。</div></div>`:''}`;$('#guideBack').disabled=state.guideStep===0;$('#guideBack').style.visibility=state.guideStep===0?'hidden':'visible';$('#guideNext').textContent=state.guideStep===total-1?'完成训练并自动记录 ✓':e?'完成此项，下一项 →':'状态正常，开始训练 →';requestAnimationFrame(()=>$('.guide-shell').scrollTo({top:0,behavior:'smooth'}))}
Move28.openGuide=n=>{state.guideDay=n;state.guideStep=0;state.guideSteps=guideStepsFor(DATA.days[n-1]);$('#guideModal').classList.add('open');$('#guideModal').setAttribute('aria-hidden','false');document.body.classList.add('body-guide-open');renderGuide();setTimeout(()=>$('.guide-close').focus(),0)};
Move28.closeGuide=()=>{$('#guideModal').classList.remove('open');$('#guideModal').setAttribute('aria-hidden','true');document.body.classList.remove('body-guide-open');workoutAudio.pause();updateMusicUI()};
Move28.guideBack=()=>{if(state.guideStep>0){state.guideStep--;renderGuide()}};
function finishGuide(){const old=state.tracker[state.guideDay]||{},next=Math.min(28,state.guideDay+1);state.tracker[state.guideDay]={...old,'日期':old['日期']||Move28.utils.localDate(),'完成状态':'已完成'};localStorage.setItem(state.storeKey,JSON.stringify(state.tracker));state.currentDay=next;localStorage.setItem('move28-current-day',state.currentDay);Move28.closeGuide();Move28.ui.renderToday();Move28.ui.renderOverview();Move28.openTrack(state.guideDay);Move28.ui.showToast(state.guideDay<28?`第${state.guideDay}天已完成；下次从第${next}天继续`:'28天计划已全部完成！')}
Move28.guideNext=()=>{if(state.guideStep<state.guideSteps.length-1){state.guideStep++;renderGuide()}else finishGuide()};
Object.assign(Move28.guide,{guideStepsFor,renderGuide,updateMusicUI,syncGuideMusic,workoutAudio,MUSIC});
for(const name of ['openGuide','closeGuide','guideBack','guideNext','toggleWorkoutMusic','setWorkoutVolume'])window[name]=Move28[name];
})(window.Move28);
