(function(window){
const Move28=window.Move28=window.Move28||{};
Move28.data=Move28.data||{};
Move28.ui=Move28.ui||{};
Move28.guide=Move28.guide||{};
Move28.state={
  currentDay:Number(localStorage.getItem('move28-current-day')||1),
  currentWeek:1,
  exerciseFilter:'全部',
  trackDay:1,
  guideDay:1,
  guideStep:0,
  guideSteps:[],
  toastTimer:null,
  clearArmTimer:null,
  clearArmed:false,
  musicEnabled:localStorage.getItem('move28-music-enabled')!=='0',
  musicKey:'',
  musicVolume:Number(localStorage.getItem('move28-music-volume')||32)/100,
  storeKey:'move28-tracker-v1',
  tracker:JSON.parse(localStorage.getItem('move28-tracker-v1')||'{}')
};
Move28.utils={
  $:s=>document.querySelector(s),
  $$:s=>[...document.querySelectorAll(s)],
  esc:s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),
  localDate:()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
};
})(window);
