'use strict';
const assert=require('node:assert/strict');
const test=require('node:test');
const{clearMove28ModuleCache,loadScript}=require('../helpers/load-script.cjs');
function api(){clearMove28ModuleCache();return loadScript('privacyTools')}
test('摘要文件名只使用受控participantId',()=>{const p=api();assert.equal(p.summaryFilename({participantId:'pilot-a1b2'}),'move28-review-summary-pilot-a1b2.json');assert.equal(p.summaryFilename({participantId:'../../secret'}),'move28-review-summary-pilot-local.json')});
test('JSON下载仅使用Blob/object URL并延迟回收',()=>{const calls=[],timers=[];let blobParts=null;const anchor={hidden:false,click(){calls.push('click')},remove(){calls.push('remove')}};const env={Blob:class{constructor(parts,options){blobParts=parts;this.type=options.type}},URL:{createObjectURL(blob){calls.push(['url',blob.type]);return'blob:local'},revokeObjectURL(url){calls.push(['revoke',url])}},document:{createElement(tag){assert.equal(tag,'a');return anchor},body:{appendChild(value){assert.equal(value,anchor);calls.push('append')}}},setTimeout(fn,delay){timers.push([fn,delay])}};const summary={participantId:'pilot-a',riskCodes:[]},result=api().downloadReviewSummary(summary,env);assert.deepEqual(result,{ok:true,status:'download_started',filename:'move28-review-summary-pilot-a.json'});assert.equal(anchor.href,'blob:local');assert.equal(anchor.download,result.filename);assert.equal(JSON.parse(blobParts[0]).participantId,'pilot-a');assert.deepEqual(calls,[['url','application/json;charset=utf-8'],'append','click','remove']);assert.equal(timers[0][1],1000);timers[0][0]();assert.deepEqual(calls.at(-1),['revoke','blob:local'])});
test('Blob URL创建后下载失败会立即回收且不伪称成功',()=>{const revoked=[];const env={Blob:class{},URL:{createObjectURL(){return'blob:failed'},revokeObjectURL(url){revoked.push(url)}},document:{createElement(){return{}},body:{appendChild(){throw new Error('SECRET')}}}};assert.deepEqual(api().downloadReviewSummary({participantId:'pilot-a'},env),{ok:false,status:'download_failed'});assert.deepEqual(revoked,['blob:failed'])});
test('下载能力缺失时固定失败且不尝试网络回退',()=>{let network=0;const result=api().downloadReviewSummary({participantId:'pilot-a'},{fetch(){network++}});assert.deepEqual(result,{ok:false,status:'download_unavailable'});assert.equal(network,0)});
test('CommonJS无sessionStorage时删除明确partial failure且不泄漏异常',()=>{const result=api().clearAllLocalData();assert.equal(result.ok,false);assert.equal(result.status,'partial_failure');assert.ok(result.failedScopes.includes('session.onboardingDraft'));assert.equal(JSON.stringify(result).includes('Error'),false)});
