'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const storeApi=require('../../src/storage/local-store.js');
const {generatePlan}=require('../../src/domain/plan-generator.js');
const {exerciseCatalog}=require('../../src/data/exercise-catalog.js');
const {capabilityInput}=require('../helpers/capability-fixture.cjs');
const intake={boundaryAccepted:true,age:30,pregnancyPostpartum:'no',goal:'habit',activityDays:'3',walkCapacity:'20_40',strengthExperience:'some',trainingBreak:'no',daysPerWeek:'2',sessionMinutes:'30',weekdays:['mon','thu'],gymOftenUnavailable:'no',setting:'gym',equipment:['stable_chair','exercise_mat','leg_press_machine','leg_curl_machine','chest_press_machine','seated_row_machine','resistance_band','cable_machine','elliptical_trainer','treadmill'],allowSettingSwap:'no',painAreas:['none'],painTrend:'none',acuteInjury:'no',unableToBearWeight:'no',visibleSwelling:'no',dailyActivityLimited:'no',chairStand:'yes',walkTenMinutes:'yes',chestSymptoms:'no',exertionalDizziness:'no',unexplainedFainting:'no',restingShortnessOfBreath:'no',unresolvedConcussion:'no',doctorRestriction:'none',recentSurgery:'no',complexCondition:'no',uncontrolledBloodPressure:'no',cardioPreference:'none',cardioAvoid:'none',avoidMovements:[],avoidEquipment:[],trackingItems:['completion'],sessionPreference:'short_frequent',musicEnabled:'no',finalConfirmed:true};
const risk={level:'normal',ruleVersion:'pilot-v2',reasons:[]};
const capability={version:1,completed:true,chairRise:'independent_controlled',wallPushup:'controlled',wallHinge:'controlled',floorAccess:'comfortable',walkTolerance:'comfortable'};
function memory(){let value=null,writes=0;return{getItem(){return value},setItem(_k,next){value=next;writes+=1},removeItem(){value=null},snapshot(){return value},writes(){return writes}}}
function approved(){const storage=memory(),store=storeApi.createLocalStore({storage,now:()=> '2030-01-02T03:04:05.000Z'});store.saveIntake(intake,risk);store.saveCapabilityProfile(capability);const generated=generatePlan({intake,risk,intakeRevision:1,catalog:exerciseCatalog,...capabilityInput()});store.savePlan(generated);const raw=JSON.parse(storage.snapshot());raw.plan.status='active';raw.plan.review={status:'approved',reviewerId:'pilot-reviewer',reviewedAt:'2030-01-01T00:00:00.000Z',planId:raw.plan.id,intakeRevision:1,capabilityRevision:1};storage.setItem(storeApi.STORAGE_KEY,JSON.stringify(raw));return{storage,store}}
function review(overrides={}){return{reviewVersion:1,weekNumber:1,completedSessions:2,completionReason:'completed',difficulty:'suitable',movementQuality:'stable',painStatus:'none',painAreas:[],painAffectsDailyActivity:false,recovery:'good',nextWeekTime:'same',...overrides}}
function approveCurrent(storage,reviewedAt='2030-01-03T00:00:00.000Z'){const raw=JSON.parse(storage.snapshot());return storeApi.createLocalStore({storage,now:()=>reviewedAt}).approvePlanReview({reviewerId:'pilot-reviewer',planId:raw.plan.id,intakeRevision:raw.intakeRevision})}
function acceptedTwoHopChain(){const current=approved(),first=current.store.recordWeeklyReview(review({difficulty:'too_hard',completionReason:'difficulty'}));current.store.resolveWeeklyReview({reviewId:first.weeklyReviews[0].id,decision:'accepted'});approveCurrent(current.storage);const second=current.store.recordWeeklyReview(review({weekNumber:2,difficulty:'too_light',nextWeekTime:'less'}));current.store.resolveWeeklyReview({reviewId:second.weeklyReviews.at(-1).id,decision:'accepted'});approveCurrent(current.storage,'2030-01-04T00:00:00.000Z');return current}

test('周复盘保存固定白名单，拒绝调整后原active计划保持不变',()=>{const{store}=approved();const saved=store.recordWeeklyReview(review());assert.equal(saved.weeklyReviews.length,1);const record=saved.weeklyReviews[0];assert.equal(record.capabilityRevision,1);assert.equal(record.decision,'pending');assert.equal(saved.plan.status,'active');assert.deepEqual(Object.keys(record.answers),['completedSessions','scheduledSessions','completionReason','difficulty','movementQuality','painStatus','painAreas','painAffectsDailyActivity','recovery','nextWeekTime']);const rejected=store.resolveWeeklyReview({reviewId:record.id,decision:'rejected'});assert.equal(rejected.weeklyReviews[0].decision,'rejected');assert.equal(rejected.plan.status,'active')});
test('接受单变量调整后生成新pending_review计划并清空旧人工复核',()=>{const{storage,store}=approved();const pending=store.recordWeeklyReview(review({difficulty:'too_hard',completionReason:'difficulty'})),record=pending.weeklyReviews[0],writes=storage.writes();const accepted=store.resolveWeeklyReview({reviewId:record.id,decision:'accepted'});assert.equal(storage.writes(),writes+1);assert.equal(accepted.weeklyReviews[0].decision,'accepted');assert.equal(accepted.plan.status,'pending_review');assert.equal(accepted.plan.review,null);assert.equal(accepted.plan.capabilityRevision,1);assert.notEqual(accepted.plan.id,record.planId);assert.equal(accepted.weeklyReviews[0].resultPlanId,accepted.plan.id);assert.equal(accepted.plan.weeks[1].sessions[0].actions[0].reps,8)});
test('接受调整并人工复核新revision后继承周期进度，只能提交下一周',()=>{const{storage,store}=approved();const first=store.recordWeeklyReview(review({difficulty:'too_hard',completionReason:'difficulty'}));const accepted=store.resolveWeeklyReview({reviewId:first.weeklyReviews[0].id,decision:'accepted'}),raw=JSON.parse(storage.snapshot());raw.plan.status='active';raw.plan.review={status:'approved',reviewerId:'pilot-reviewer',reviewedAt:'2030-01-03T00:00:00.000Z',planId:raw.plan.id,intakeRevision:1,capabilityRevision:1};storage.setItem(storeApi.STORAGE_KEY,JSON.stringify(raw));assert.throws(()=>store.recordWeeklyReview(review({weekNumber:1,difficulty:'too_hard',completionReason:'difficulty'})),/Unable to save/);const second=store.recordWeeklyReview(review({weekNumber:2}));assert.equal(second.weeklyReviews.at(-1).weekNumber,2);assert.equal(second.weeklyReviews.at(-1).planId,accepted.plan.id)});
test('两次接受调整形成三代计划，刷新store后仅继承validated lineage并允许第3周连续过轻进阶',()=>{const{storage}=acceptedTwoHopChain();const refreshed=storeApi.createLocalStore({storage,now:()=> '2030-01-05T00:00:00.000Z'}),loaded=refreshed.loadState();assert.equal(loaded.weeklyReviews.length,2);assert.equal(loaded.weeklyReviews[0].resultPlanId,loaded.weeklyReviews[1].planId);assert.equal(loaded.weeklyReviews[1].resultPlanId,loaded.plan.id);for(const weekNumber of [1,2,4])assert.throws(()=>refreshed.recordWeeklyReview(review({weekNumber,difficulty:'too_light'})),error=>error.name==='StorageError'&&error.message==='Unable to save local participant state');const third=refreshed.recordWeeklyReview(review({weekNumber:3,completedSessions:1,difficulty:'too_light'}));assert.equal(third.weeklyReviews.at(-1).weekNumber,3);assert.equal(third.weeklyReviews.at(-1).proposal.type,'progress_one_variable');assert.equal(third.weeklyReviews.at(-1).proposal.reasonCode,'light_streak_progress_reps')});
test('详细复核材料提供可信脱敏的周调整lineage摘要',()=>{const{store}=acceptedTwoHopChain();const dossier=store.buildDetailedReviewDossier();assert.equal(dossier.lineage.validationResult,'passed');assert.equal(dossier.lineage.currentPlanId,dossier.planId);assert.equal(dossier.lineage.acceptedEdges.length,2);assert.deepEqual(dossier.lineage.acceptedEdges.map(edge=>edge.weekNumber),[1,2]);assert.equal(dossier.lineage.acceptedEdges[0].resultPlanId,dossier.lineage.acceptedEdges[1].sourcePlanId);assert.equal(dossier.lineage.acceptedEdges[1].resultPlanId,dossier.planId);assert.ok(dossier.lineage.acceptedEdges.every(edge=>edge.capabilityRevision===dossier.capabilityRevision));assert.equal(JSON.stringify(dossier.lineage).includes('answers'),false)});
test('断链、跨能力revision、非法自环、重复、分叉或断开accepted边都不能继承周次或过轻streak',()=>{for(const [label,mutate]of [
  ['broken',raw=>{raw.weeklyReviews[1].resultPlanId='broken-child'}],
  ['cross-capability',raw=>{raw.weeklyReviews[1].capabilityRevision=2}],
  ['invalid-self-edge',raw=>{raw.weeklyReviews[1].resultPlanId=raw.weeklyReviews[1].planId}],
  ['duplicate',raw=>{raw.weeklyReviews.push({...structuredClone(raw.weeklyReviews[0]),id:'weekly.duplicate'})}],
  ['fork',raw=>{const parent=raw.weeklyReviews[0];raw.weeklyReviews.push({...structuredClone(parent),id:'weekly.fork',weekNumber:4,resultPlanId:`${parent.planId}-w4-a`})}],
  ['disconnected',raw=>{raw.weeklyReviews.push({...structuredClone(raw.weeklyReviews[0]),id:'weekly.disconnected',planId:'detached-parent',resultPlanId:'detached-parent-w1-a'})}]
]){const{storage}=acceptedTwoHopChain(),raw=JSON.parse(storage.snapshot());mutate(raw);storage.setItem(storeApi.STORAGE_KEY,JSON.stringify(raw));const refreshed=storeApi.createLocalStore({storage,now:()=> '2030-01-05T00:00:00.000Z'}),before=storage.snapshot();assert.throws(()=>refreshed.buildDetailedReviewDossier(),error=>error.name==='StorageError',label);assert.throws(()=>refreshed.recordWeeklyReview(review({weekNumber:3,completedSessions:1,difficulty:'too_light'})),error=>error.name==='StorageError'&&error.message==='Unable to save local participant state',label);assert.equal(storage.snapshot(),before,label);const restarted=refreshed.recordWeeklyReview(review({weekNumber:1,difficulty:'too_light'}));assert.equal(restarted.weeklyReviews.at(-1).proposal.type,'keep',label)}});
test('旧版accepted记录缺少resultPlanId时按确定性revision规则迁移并保留周进度',()=>{const{storage,store}=approved();const first=store.recordWeeklyReview(review({difficulty:'too_hard',completionReason:'difficulty'}));store.resolveWeeklyReview({reviewId:first.weeklyReviews[0].id,decision:'accepted'});const raw=JSON.parse(storage.snapshot());delete raw.weeklyReviews[0].resultPlanId;raw.plan.status='active';raw.plan.review={status:'approved',reviewerId:'pilot-reviewer',reviewedAt:'2030-01-03T00:00:00.000Z',planId:raw.plan.id,intakeRevision:1,capabilityRevision:1};storage.setItem(storeApi.STORAGE_KEY,JSON.stringify(raw));const migrated=store.loadState();assert.equal(migrated.weeklyReviews.length,1);assert.equal(migrated.weeklyReviews[0].resultPlanId,migrated.plan.id);assert.throws(()=>store.recordWeeklyReview(review({weekNumber:1,difficulty:'too_hard',completionReason:'difficulty'})),/Unable to save/);assert.equal(store.recordWeeklyReview(review({weekNumber:2})).weeklyReviews.at(-1).weekNumber,2)});
test('显式伪造resultPlanId不能建立lineage或跳过周次',()=>{const{storage,store}=approved();const first=store.recordWeeklyReview(review({difficulty:'too_hard',completionReason:'difficulty'}));store.resolveWeeklyReview({reviewId:first.weeklyReviews[0].id,decision:'accepted'});const raw=JSON.parse(storage.snapshot());raw.weeklyReviews[0].planId='forged-parent';raw.weeklyReviews[0].resultPlanId=raw.plan.id;raw.plan.status='active';raw.plan.review={status:'approved',reviewerId:'pilot-reviewer',reviewedAt:'2030-01-03T00:00:00.000Z',planId:raw.plan.id,intakeRevision:1,capabilityRevision:1};storage.setItem(storeApi.STORAGE_KEY,JSON.stringify(raw));assert.equal(store.loadState().weeklyReviews.length,0);assert.throws(()=>store.recordWeeklyReview(review({weekNumber:2})),/Unable to save/);assert.equal(store.recordWeeklyReview(review({weekNumber:1})).weeklyReviews.at(-1).weekNumber,1)});
test('新发疼痛原子记录rescreen并让计划stale，不能保持原计划',()=>{const{store}=approved();const state=store.recordWeeklyReview(review({painStatus:'new',painAreas:['knee']}));assert.equal(state.weeklyReviews[0].decision,'rescreen');assert.equal(state.plan.status,'stale');assert.equal(state.plan.staleReason,'weekly_pain_rescreen');assert.throws(()=>store.resolveWeeklyReview({reviewId:state.weeklyReviews[0].id,decision:'rejected'}),/Unable to save/)});
test('同计划同周不能重复提交，Task11 stale计划不能进入周复盘',()=>{const first=approved();first.store.recordWeeklyReview(review());assert.throws(()=>first.store.recordWeeklyReview(review()),/Unable to save/);const second=approved(),raw=JSON.parse(second.storage.snapshot());raw.plan.status='stale';raw.plan.staleReason='runtime-safety-event';raw.plan.staleAt='2030-01-02T03:04:05.000Z';second.storage.setItem(storeApi.STORAGE_KEY,JSON.stringify(raw));assert.throws(()=>second.store.recordWeeklyReview(review()),/Unable to save/)});
test('迁移只恢复周复盘白名单且审核摘要不泄漏答案',()=>{const{storage,store}=approved();store.recordWeeklyReview(review({difficulty:'too_hard'}));const raw=JSON.parse(storage.snapshot());raw.weeklyReviews[0].answers.note='private';raw.weeklyReviews[0].proposal.freeText='private';storage.setItem(storeApi.STORAGE_KEY,JSON.stringify(raw));const loaded=store.loadState(),record=loaded.weeklyReviews[0];assert.equal('note'in record.answers,false);assert.equal('freeText'in record.proposal,false);const summary=store.exportReviewSummary();assert.equal('weeklyReviewCount'in summary,false);assert.equal(JSON.stringify(summary).includes('too_hard'),false)});
test('未决定建议阻止提交下一周，关闭建议不能绕过决定流程',()=>{const{store}=approved();store.recordWeeklyReview(review());assert.throws(()=>store.recordWeeklyReview(review({weekNumber:2})),/Unable to save/)});
test('迁移恢复weekly重筛的计划失效跨字段不变量',()=>{const{storage,store}=approved();const stale=store.recordWeeklyReview(review({painStatus:'new',painAreas:['knee']})),raw=JSON.parse(storage.snapshot());raw.plan.status='active';delete raw.plan.staleReason;delete raw.plan.staleAt;storage.setItem(storeApi.STORAGE_KEY,JSON.stringify(raw));const loaded=store.loadState();assert.equal(loaded.plan.status,'stale');assert.equal(loaded.plan.staleReason,'weekly_pain_rescreen');assert.equal(loaded.plan.staleAt,stale.weeklyReviews[0].decidedAt)});
test('weekly写入失败不伪称成功且原字节保持不变',()=>{const base=approved(),before=base.storage.snapshot();const failing={getItem:()=>before,setItem(){throw new Error('SECRET')},removeItem(){}};const store=storeApi.createLocalStore({storage:failing,now:()=> '2030-01-02T03:04:05.000Z'});assert.throws(()=>store.recordWeeklyReview(review()),error=>error.name==='StorageError'&&!error.message.includes('SECRET'));assert.equal(base.storage.snapshot(),before)});
