'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const {generatePlan}=require('../../src/domain/plan-generator.js');
const {exerciseCatalog}=require('../../src/data/exercise-catalog.js');
const adaptation=require('../../src/domain/weekly-adaptation.js');
const {capabilityInput}=require('../helpers/capability-fixture.cjs');

const intake={age:30,finalConfirmed:true,daysPerWeek:'2',sessionMinutes:'30',weekdays:['mon','thu'],setting:'gym',equipment:['stable_chair','exercise_mat','leg_press_machine','leg_curl_machine','chest_press_machine','seated_row_machine','resistance_band','cable_machine','elliptical_trainer','treadmill'],avoidMovements:[],avoidEquipment:[],cardioPreference:'none',cardioAvoid:'none',strengthExperience:'some',trainingBreak:'no',allowSettingSwap:'no'};
const risk={level:'normal',ruleVersion:'pilot-v2',reasons:[]};
function activePlan(level='normal'){
  const generated=generatePlan({intake,risk:{...risk,level},intakeRevision:1,catalog:exerciseCatalog,...capabilityInput()});
  const plan=structuredClone(generated);plan.status='active';plan.review={status:'approved',reviewerId:'pilot-reviewer',reviewedAt:'2030-01-02T03:04:05.000Z',planId:plan.id,intakeRevision:1,capabilityRevision:1};return plan;
}
function review(overrides={}){return{reviewVersion:1,weekNumber:1,completedSessions:2,completionReason:'completed',difficulty:'suitable',movementQuality:'stable',painStatus:'none',painAreas:[],painAffectsDailyActivity:false,recovery:'good',nextWeekTime:'same',...overrides}}
function propose(plan,weeklyReview,previousReviews=[]){return adaptation.proposeWeeklyChange({plan,review:weeklyReview,previousReviews,intake,risk:{...risk,level:plan.riskLevel},...capabilityInput()})}

test('合适且恢复正常时保持原计划，不修改输入',()=>{const plan=activePlan(),before=structuredClone(plan),result=propose(plan,review());assert.equal(result.type,'keep');assert.equal(result.reason,'suitable_keep');assert.equal(result.after,null);assert.deepEqual(plan,before)});
test('时间不足只减少下一周一个session变量',()=>{const plan=activePlan(),result=propose(plan,review({completedSessions:1,completionReason:'time',nextWeekTime:'less'}));assert.equal(result.type,'reduce');assert.equal(result.variable,'session_count');assert.equal(result.targetWeekNumber,2);assert.equal(result.after.weeks[1].sessions.length,plan.weeks[1].sessions.length-1);assert.deepEqual(result.after.weeks[0],plan.weeks[0]);assert.deepEqual(result.after.weeks[2],plan.weeks[2])});
test('过难只采用第一个可通过硬校验的减量变量',()=>{const plan=activePlan(),result=propose(plan,review({difficulty:'too_hard',completionReason:'difficulty'}));assert.equal(result.type,'reduce');assert.equal(result.variable,'reps');for(const [i,action]of result.after.weeks[1].sessions.flatMap(s=>s.actions).entries())assert.equal(action.reps,plan.weeks[1].sessions.flatMap(s=>s.actions)[i].reps-1)});
test('恢复差绝不进阶',()=>{const result=propose(activePlan(),review({difficulty:'too_light',recovery:'poor'}),[{planId:'x'}]);assert.notEqual(result.type,'progress_one_variable')});
test('单周过轻不进阶，连续两周过轻且动作稳定才仅增加reps',()=>{const plan=activePlan();assert.equal(propose(plan,review({weekNumber:2,difficulty:'too_light'})).type,'keep');const previous=[{planId:'accepted-parent',intakeRevision:1,capabilityRevision:1,weekNumber:1,answers:{completedSessions:2,scheduledSessions:2,difficulty:'too_light',movementQuality:'stable',painStatus:'none',recovery:'good'}}];const result=propose(plan,review({weekNumber:2,difficulty:'too_light'}),previous);assert.equal(result.type,'progress_one_variable');assert.equal(result.variable,'reps');for(const [i,action]of result.after.weeks[2].sessions.flatMap(s=>s.actions).entries())assert.equal(action.reps,plan.weeks[2].sessions.flatMap(s=>s.actions)[i].reps+1)});
test('conservative用户连续过轻仍不自动进阶',()=>{const plan=activePlan('conservative'),previous=[{planId:plan.id,intakeRevision:1,weekNumber:0,answers:{completedSessions:2,scheduledSessions:2,difficulty:'too_light',movementQuality:'stable',painStatus:'none',recovery:'good'}}];assert.notEqual(propose(plan,review({difficulty:'too_light'}),previous).type,'progress_one_variable')});
test('新发/加重疼痛或影响日常活动始终优先重新筛查',()=>{for(const overrides of [{painStatus:'new',painAreas:['knee']},{painStatus:'worsened',painAreas:['lower_back']},{painStatus:'stable',painAreas:['knee'],painAffectsDailyActivity:true}]){const result=propose(activePlan(),review({...overrides,difficulty:'too_light',completionReason:'time'}));assert.equal(result.type,'rescreen');assert.equal(result.after,null);assert.equal(result.reason,'new_or_worsening_pain')}});
test('第4周只记录周期结束，不生成第5周',()=>{const result=propose(activePlan(),review({weekNumber:4}));assert.equal(result.type,'keep');assert.equal(result.reason,'cycle_complete');assert.equal(result.targetWeekNumber,null)});
test('非active、revision错、安全stale、非法review均fail closed',()=>{for(const mutate of [p=>p.status='pending_review',p=>p.intakeRevision=2,p=>p.review.capabilityRevision=2,p=>delete p.review.capabilityRevision,p=>{p.status='stale';p.staleReason='runtime-safety-event'}]){const plan=activePlan();mutate(plan);assert.equal(propose(plan,review()).status,'unavailable')}assert.equal(propose(activePlan(),review({completedSessions:99})).status,'unavailable');assert.equal(propose(activePlan(),review({completedSessions:1,completionReason:'completed'})).status,'unavailable')});
test('错误历史不计入连续过轻，结果确定且深冻结',()=>{const plan=activePlan(),bad=[{planId:'other',intakeRevision:1,capabilityRevision:2,weekNumber:0,answers:{completedSessions:2,scheduledSessions:2,difficulty:'too_light',movementQuality:'stable',painStatus:'none',recovery:'good'}}];const a=propose(plan,review({difficulty:'too_light'}),bad),b=propose(plan,review({difficulty:'too_light'}),bad);assert.deepEqual(a,b);assert.equal(a.type,'keep');assert.equal(Object.isFrozen(a),true);assert.throws(()=>{a.type='evil'},TypeError)});
test('非法当前计划在keep、周期结束和疼痛重筛路径也不能绕过完整validator',()=>{for(const overrides of [{},{weekNumber:4},{painStatus:'new',painAreas:['knee']}]){const plan=activePlan();plan.weeks[0].sessions[0].actions[0].reps=999;assert.equal(propose(plan,review(overrides)).status,'unavailable')}});
test('调整入口以完整validator硬拒绝能力difficultyCap、排除、variant及首周/后续有氧剂量违规',()=>{const invalidPlanCases=[
  plan=>{plan.weeks[0].sessions[0].actions[0].reps=999},
  plan=>{plan.weeks[0].sessions[0].actions.find(action=>action.pattern==='knee_dominant').variant='high_seat'}
];for(const mutate of invalidPlanCases){const plan=activePlan();mutate(plan);const result=propose(plan,review({difficulty:'too_hard',completionReason:'difficulty'}));assert.equal(result.status,'unavailable');assert.equal(result.code,'PLAN_VALIDATION_FAILED');assert.equal(result.after,null)}const excluded=adaptation.proposeWeeklyChange({plan:activePlan(),review:review(),previousReviews:[],intake:{...intake,avoidMovements:['knee_dominant']},risk,...capabilityInput()});assert.equal(excluded.code,'PLAN_VALIDATION_FAILED');assert.equal(excluded.after,null);const conservativeCapability={status:'conservative',difficultyCap:1,exclusions:[],variants:{knee_dominant:'standard',horizontal_push:'standard'},cardioStartMinutes:15,reasonCodes:['CHAIR_RISE_HANDS_SUPPORTED']},difficulty=adaptation.proposeWeeklyChange({plan:activePlan(),review:review(),previousReviews:[],intake,risk,capabilityResult:conservativeCapability,capabilityRevision:1});assert.equal(difficulty.code,'PLAN_VALIDATION_FAILED');assert.equal(difficulty.after,null);const cardioIntake={...intake,daysPerWeek:'3',weekdays:['mon','wed','fri'],cardioPreference:'flat_walk'},generated=generatePlan({intake:cardioIntake,risk,intakeRevision:1,catalog:exerciseCatalog,...capabilityInput()}),cardioPlan=structuredClone(generated);cardioPlan.status='active';cardioPlan.review={status:'approved',reviewerId:'pilot-reviewer',reviewedAt:'2030-01-02T03:04:05.000Z',planId:cardioPlan.id,intakeRevision:1,capabilityRevision:1};for(const [weekIndex,durationMin]of [[0,20],[1,999]]){const plan=structuredClone(cardioPlan),cardio=plan.weeks[weekIndex].sessions.find(session=>session.intent==='low_impact_cardio');assert.ok(cardio);cardio.actions[0].durationMin=durationMin;const result=adaptation.proposeWeeklyChange({plan,review:review(),previousReviews:[],intake:cardioIntake,risk,...capabilityInput()});assert.equal(result.code,'PLAN_VALIDATION_FAILED');assert.equal(result.after,null)}});
test('validator返回getter结果时零getter执行且fail closed',()=>{const source=fs.readFileSync(path.join(__dirname,'../../src/domain/weekly-adaptation.js'),'utf8'),input=JSON.stringify({plan:activePlan(),review:review(),intake,risk}),catalog=JSON.stringify(exerciseCatalog),context=vm.createContext({input,catalog,reads:0});vm.runInContext("globalThis.structuredClone=value=>JSON.parse(JSON.stringify(value));globalThis.Move28={domain:{validatePlan(){const result={errors:[]};Object.defineProperty(result,'ok',{enumerable:true,get(){reads+=1;throw new Error('SECRET')}});return result}},data:{exerciseCatalog:JSON.parse(catalog)}}",context);vm.runInContext(source,context);const status=vm.runInContext('Move28.domain.proposeWeeklyChange(JSON.parse(input)).status',context);assert.equal(status,'unavailable');assert.equal(context.reads,0)});
test('getter、Proxy、稀疏数组和循环输入零执行且fail closed',()=>{let reads=0;const hostile=review();Object.defineProperty(hostile,'difficulty',{enumerable:true,get(){reads+=1;return'too_light'}});assert.equal(propose(activePlan(),hostile).status,'unavailable');assert.equal(reads,0);assert.doesNotThrow(()=>assert.equal(propose(activePlan(),new Proxy(review(),{ownKeys(){throw new Error('SECRET')}})).status,'unavailable'));const sparse=review();sparse.painAreas=new Array(2);assert.equal(propose(activePlan(),sparse).status,'unavailable');const cycle=review();cycle.self=cycle;assert.equal(propose(activePlan(),cycle).status,'unavailable')});
